version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/portfolio
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
