version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Build stage running..."
  post_build:
    commands:
      - echo "Build completed!"
artifacts:
  files:
    - '**/*'
